{
 "title": "IntelliSupport AI Metrics",
 "tags": [ "spring-boot" ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Tickets Created",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 9 },
   "targets": [
    { "expr": "tickets_total" }
   ]
  },
  {
   "title": "AI Resolved Tickets",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 9 },
   "targets": [
    { "expr": "tickets_resolved_ai_total" }
   ]
  },
  {
   "title": "Escalated to Human",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 9 },
   "targets": [
    { "expr": "tickets_escalated_total" }
   ]
  },
  {
   "title": "Failed / DLQ",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 9 },
   "targets": [
    { "expr": "tickets_failed_dlq_total" }
   ]
  }
 ]
}